# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: prime.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'prime.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bprime.proto\x12\x05prime\"\x1a\n\x0cPrimeRequest\x12\n\n\x02ns\x18\x01 \x03(\x05\"\x1f\n\rPrimeResponse\x12\x0e\n\x06primes\x18\x01 \x03(\x03\x32H\n\x0cPrimeService\x12\x38\n\tGetPrimes\x12\x13.prime.PrimeRequest\x1a\x14.prime.PrimeResponse\"\x00\x42\tZ\x07./protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'prime_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007./proto'
  _globals['_PRIMEREQUEST']._serialized_start=22
  _globals['_PRIMEREQUEST']._serialized_end=48
  _globals['_PRIMERESPONSE']._serialized_start=50
  _globals['_PRIMERESPONSE']._serialized_end=81
  _globals['_PRIMESERVICE']._serialized_start=83
  _globals['_PRIMESERVICE']._serialized_end=155
# @@protoc_insertion_point(module_scope)
